### PR TITLE
Fix additional fbcode-kuduraft linking issues

### PR DESCRIPTION
**Pull request by mpercy**
Two additional fixes to be able to use Messenger for RPCs and test_macros.h outside of Kudu

### CODE REVIEW

**Review by anirbanr-fb — COMMENTED** [review]
isn't the issue about using free floating (unqualified ) SERVER and CLIENT. I am asking whether the separate header file is actually necessary.

**Comment by mpercy** [comment]
> isn't the issue about using free floating (unqualified ) SERVER and CLIENT.

No, the main issue is this in messenger.h:

```
ThreadPool* negotiation_pool(Connection::Direction dir);
```

(sorry about the noise in the rest of the patch, I tried to leave it relatively clean but that inflated the LOC of the patch)

**Review by anirbanr-fb — APPROVED** [review]

**Review by anirbanr-fb — COMMENTED** [review]
removing comment as duplicate.

**Review by anirbanr-fb — COMMENTED** [review]
I think for readability and completeness standpoint auto is not a good thing.
It is lossy in knowledge and makes c++ look like python like untyped language. This is  a nit, because its in these
#defines, but in general I feel we should not use auto.

**Comment by mpercy** [comment]
> in general I feel we should not use auto.

I don't like auto for short things like string, int64_t, etc, but for really long things it's helpful. In this case, the header was already using c++11 features (it already had auto in the file) but I can see the readability benefit of ::kudu::Status as well. Since this doesn't sound like a major concern from you in this case I'm going to go ahead and merge this.

**Pull request merged**
