### PR TITLE
[time-manager] ability to disable time manager features in kudu

### PR DESCRIPTION
**Pull request by bhatvinay**
Summary:
This is mostly used in kudu for HLC support which we are not making use
of. This avoids dependency on NTP clock synchronization and also avoid
taking some hot locks.

Test Plan:
tests in fbcode

Reviewers: arahut

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by anirbanr-fb — COMMENTED** [review]
Instead of doing a disable and returning Status::OK from methods would
it be better to not create time_manager_ at all in Consensus and PeerMessageQueue and PendingRounds. The number of places time_manager_ calls are invoked can be guarded with if (time_manager_)  check

Somehow creating it and blanking out all the calls might still depend on the callers expectation.
The other issue is that disable_ is not protected by a mutex and not an atomic,
so Disable() is not thread safe and only can be called before use by other threads.

**Comment by bhatvinay** [comment]
> Instead of doing a disable and returning Status::OK from methods would it be better to not create time_manager_ at all in Consensus and PeerMessageQueue and PendingRounds. The number of places time_manager_ calls are invoked can be guarded with if (time_manager_) check

I thought of this, but there are a lot of DCHECKs that time manager is created. The number of call sites for time_manager is also spread out in multiple places.
 
> Somehow creating it and blanking out all the calls might still depend on the callers expectation. The other issue is that disable_ is not protected by a mutex and not an atomic, so Disable() is not thread safe and only can be called before use by other threads.

The 'disable' is through options and need to happen during starting kuduraft. I do not plan to have the support to enable/disable on the fly as it is not possible to gauge the state of the clock when it has been disabled for long. Given this, I think it is safe for it to be not atomic. I can make it atomic if you still think that makes it safer

**Review by anirbanr-fb — COMMENTED** [review]
I am guessing you have done the necessary code audits to make sure erstwhile
TimeManager clock skew checks no more get exercised. If you want more confidence
you can CHECK(false) in the clock skew code and run it in test environments.

**Review by anirbanr-fb — APPROVED** [review]

**Comment by bhatvinay** [comment]
> If you want more confidence you can CHECK(false) in the clock skew code and run it in test environments.

Ran all the unit tests and integration tests with this change and saw no issues with this fix.
Running a new binary in prod test setups to validate before landing

**Comment by mpercy** [comment]
Sorry if this is a little late to the game. Can we just use the logical clock instead of the hybrid clock?

**Comment by bhatvinay** [comment]
> Sorry if this is a little late to the game. Can we just use the logical clock instead of the hybrid clock?

Planning to do that too. But I still want to remove time manager functionality for the time being as it simply adds additional locking and signalling overhead:

    finish_task_switch
    __sched_text_start
    schedule
    futex_wait_queue_me
    futex_wait
    do_futex
    __x64_sys_futex
    do_syscall_64
    entry_SYSCALL_64_after_hwframe
    base::internal::SpinLockDelay(int volatile*, int, int)
    base::SpinLock::SlowLock()
    kudu::consensus::TimeManager::AdvanceSafeTimeWithMessage(kudu::consensus::ReplicateMsg const&)
    kudu::consensus::PendingRounds::AdvanceCommittedIndex(long)
    kudu::consensus::RaftConsensus::NotifyCommitIndex(long)
    kudu::consensus::PeerMessageQueue::NotifyObserversTask(std::function<void (kudu::consensus::PeerMessageQueueObserver*)> const&)
    kudu::internal::Invoker<2, kudu::internal::BindState<kudu::internal::RunnableAdapter<void (kudu::consensus::PeerMessageQueue::*)(std::function<void (kudu::consensus::PeerMessageQueueObserver*)> const&)>, void (kudu::consensus::PeerMessageQueue*, std::function<void (kudu::consensus::PeerMessageQueueObserver*)> const&), void (kudu::internal::UnretainedWrapper<kudu::consensus::PeerMessageQueue>, kudu::consensus::PeerMessageQueue::NotifyObserversOfCommitIndexChange(long)::{lambda(kudu::consensus::PeerMessageQueueObserver*)#1})>, void (kudu::consensus::PeerMessageQueue*, std::function<void (kudu::consensus::PeerMessageQueueObserver*)> const&)>::Run(kudu::internal::BindStateBase*)
    kudu::ThreadPool::DispatchThread()
    kudu::Thread::SuperviseThread(void*)
    start_thread
    __clone
    -                raft [worker]-1 (1196221)
        398

**Pull request merged**
